package com.feedme.views;

import com.feedme.Global;
import com.feedme.process.OrderProcess;
import com.feedme.service.Employee;
import com.feedme.service.EmployeeDTO;
import com.feedme.service.OrderDetail;
import com.feedme.service.OrderDetailDTO;
import com.feedme.service.OrderStatus;
import com.feedme.ws.Methods;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BHT
 */
public class OrderPanel extends javax.swing.JPanel {

    private Timer timer;
    /**
     * Creates new form OrderPanel
     */
    private DefaultTableModel model;
    private DefaultListModel listModel;
    private DefaultListModel listProcessModel;
    private OrderDetailDTO orderSelected;

    public OrderPanel() {
        initComponents();
        jSeparator1.setOrientation(SwingConstants.VERTICAL);
        orderPanelComponentsContructor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNewOrder = new org.jdesktop.swingx.JXList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listProcessingOrder = new org.jdesktop.swingx.JXList();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerTel = new javax.swing.JTextField();
        txtCustomerAddr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrderDetail = new org.jdesktop.swingx.JXTable();
        lblDiscount = new javax.swing.JLabel();
        btnReceiveOrder = new javax.swing.JButton();
        cbbOrderStatus = new javax.swing.JComboBox();
        btnUpdateOrder = new javax.swing.JButton();
        btnAddFood = new javax.swing.JButton();
        btnRemoveFood = new javax.swing.JButton();
        btnAddFoods = new javax.swing.JButton();
        btnDiscount = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Order mới");

        listNewOrder.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listNewOrder.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        listNewOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNewOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listNewOrder);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Thông tin order");

        jLabel3.setText("Khách hàng");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Order đang xử lý");

        listProcessingOrder.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listProcessingOrder.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        listProcessingOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProcessingOrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listProcessingOrder);

        jLabel5.setText("Điện thoại");

        jLabel6.setText("Địa chỉ");

        tblOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Món Ăn", "Giá Tiền", "Chọn/Bỏ Chọn", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrderDetail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jScrollPane3.setViewportView(tblOrderDetail);

        lblDiscount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiscount.setText("69.969 VND");

        btnReceiveOrder.setText("Nhận order");
        btnReceiveOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveOrderActionPerformed(evt);
            }
        });

        cbbOrderStatus.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbbOrderStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbOrderStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbOrderStatusItemStateChanged(evt);
            }
        });
        cbbOrderStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbOrderStatusMouseClicked(evt);
            }
        });

        btnUpdateOrder.setText("Cập nhật");
        btnUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderActionPerformed(evt);
            }
        });

        btnAddFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/feedme/img/plus.png"))); // NOI18N
        btnAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodActionPerformed(evt);
            }
        });

        btnRemoveFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/feedme/img/substract.png"))); // NOI18N
        btnRemoveFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFoodActionPerformed(evt);
            }
        });

        btnAddFoods.setText("Thêm món");
        btnAddFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodsActionPerformed(evt);
            }
        });

        btnDiscount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/feedme/img/sale.png"))); // NOI18N
        btnDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscountActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/feedme/img/signout.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddFood, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveFood, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddFoods))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCustomer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtCustomerTel)))
                    .addComponent(txtCustomerAddr)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReceiveOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDiscount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDiscount))
                            .addComponent(cbbOrderStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddFood)
                            .addComponent(btnRemoveFood)
                            .addComponent(btnAddFoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiscount)
                            .addComponent(btnDiscount))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbbOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnReceiveOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderActionPerformed
        System.out.println(Global.IS_SELECTED_PRODUCT);
    }//GEN-LAST:event_btnUpdateOrderActionPerformed

    private void btnAddFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodsActionPerformed
        OrderInternalFrame oif = new OrderInternalFrame();
        oif.setVisible(true);
    }//GEN-LAST:event_btnAddFoodsActionPerformed

    private void btnDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountActionPerformed
        SaleInternalFrame frame = new SaleInternalFrame();
        frame.setVisible(true);

    }//GEN-LAST:event_btnDiscountActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        CardLayout layout = (CardLayout) this.getParent().getLayout();
        layout.show(this.getParent(), "staff");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRemoveFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFoodActionPerformed
        // TODO add your handling code here:
        // System.out.println(Global.IS_SELECTED_PRODUCT);
        loadOrderTable();
    }//GEN-LAST:event_btnRemoveFoodActionPerformed

    private void listNewOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNewOrderMouseClicked
        // TODO add your handling code here:
        cbbOrderStatus.setEnabled(false);
        if (evt.getClickCount() == 2) {
            JOptionPane.showMessageDialog(null, "Loading....");
            Global.ORDER = OrderProcess.getOrderDetail((String) listNewOrder.getSelectedValue());
            loadOrderData(Global.ORDER);
        }
    }//GEN-LAST:event_listNewOrderMouseClicked

    private void cbbOrderStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbOrderStatusMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbbOrderStatusMouseClicked

    private void cbbOrderStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbOrderStatusItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbbOrderStatusItemStateChanged

    private void btnReceiveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveOrderActionPerformed
        // TODO add your handling code here:
        OrderDetail order = Global.ORDER;
        Employee em = Global.EMPLOYEE.getEmployee();
        Global.ORDER_STATUS = OrderProcess.getOrderStatus((String) cbbOrderStatus.getSelectedItem());
        receivedOrderByEmployee(order, em, Global.ORDER_STATUS);
        //  JOptionPane.showMessageDialog(null, Global.ORDER_STATUS.getName());

    }//GEN-LAST:event_btnReceiveOrderActionPerformed

    private void listProcessingOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProcessingOrderMouseClicked
        // TODO add your handling code here:
        cbbOrderStatus.setEnabled(false);
        btnReceiveOrder.setEnabled(true);
        if (evt.getClickCount() == 2) {
            Global.ORDER = OrderProcess.getOrderDetail((String) listProcessingOrder.getSelectedValue());
            loadOrderData(Global.ORDER);
        }
    }//GEN-LAST:event_listProcessingOrderMouseClicked

    private void btnAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodActionPerformed
        // TODO add your handling code here:
        initOderProcessList();
    }//GEN-LAST:event_btnAddFoodActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFood;
    private javax.swing.JButton btnAddFoods;
    private javax.swing.JButton btnDiscount;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReceiveOrder;
    private javax.swing.JButton btnRemoveFood;
    private javax.swing.JButton btnUpdateOrder;
    private javax.swing.JComboBox cbbOrderStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDiscount;
    private org.jdesktop.swingx.JXList listNewOrder;
    private org.jdesktop.swingx.JXList listProcessingOrder;
    private org.jdesktop.swingx.JXTable tblOrderDetail;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtCustomerAddr;
    private javax.swing.JTextField txtCustomerTel;
    // End of variables declaration//GEN-END:variables

    private void loadOrderTable() {
        //model.setRowCount(0);
        Global.ORDERPROD_TABLE_MODEL.setRowCount(0);
        tblOrderDetail.setModel(Global.ORDERPROD_TABLE_MODEL);
    }

    private void loadOrderStatus() {
        cbbOrderStatus.setModel(OrderProcess.initOrderStatusCbbModel());
    }

    private void initNewOderList() {

        new Thread(() -> {
            listModel.clear();
            listModel = OrderProcess.initNewOrderListModel();
            listNewOrder.setModel(listModel);
        }).start();
    }

    private void initOderProcessList() {
        new Thread(() -> {
            listProcessModel.clear();
            listProcessModel = OrderProcess.initOrderProcessListModel();
            listProcessingOrder.setModel(listProcessModel);
        }).start();
    }

    private void loadOrderData(OrderDetail order) {
        new Thread(() -> {
            HashMap<String, String> map = OrderProcess.getInformation(order);
            txtCustomer.setText(map.get("Name"));
            txtCustomerAddr.setText(map.get("Address"));
            txtCustomerTel.setText(map.get("Tel"));
            cbbOrderStatus.setSelectedItem(order.getStatus().getName());
            JOptionPane.showMessageDialog(null, "Đơn Hàng Số " + order.getId() + "\nTrạng Thái Đơn Hàng \n" + cbbOrderStatus.getSelectedItem().toString());
        }).start();
        cbbOrderStatus.setEnabled(true);
        btnReceiveOrder.setEnabled(true);

    }

    private void reloadNewOrderList() {
        timer = new Timer(60000, (ActionEvent e) -> {
            initNewOderList();
            //initOderProcessList();
            System.out.println(">_ Auto Update Order running .....");

        });
    }

    /**
     * Important!!!
     *
     */
    //Methods in Contructor
    private void orderPanelComponentsContructor() {
        // model = new DefaultTableModel(new Object[]{"Món ăn", "SL", "Giá"}, 0);
        listModel = new DefaultListModel();
        listProcessModel = new DefaultListModel();

        listNewOrder.setModel(listModel);
        listProcessingOrder.setModel(listProcessModel);
        Global.ORDERPROD_TABLE_MODEL = (DefaultTableModel) tblOrderDetail.getModel();
        loadOrderStatus();
        initNewOderList();
        initOderProcessList();
        reloadNewOrderList();
        cbbOrderStatus.setEnabled(false);
        btnReceiveOrder.setEnabled(false);
        timer.start();
    }

    private void receivedOrderByEmployee(OrderDetail order, Employee em, OrderStatus ORDER_STATUS) {
        boolean result = OrderProcess.receivesOrder(order, em, ORDER_STATUS, "", 0.0);
        if (result) {
            JOptionPane.showMessageDialog(null, "Đơn hàng " + order.getId() + "\n Đã được nhận bởi nhân viên " + em.getUsername());
            initNewOderList();
            initOderProcessList();
        } else {
            JOptionPane.showMessageDialog(null, "Nhận đơn hàng lỗi. \n ");
        }
    }
}
