package com.feedme.views;

import com.feedme.Global;
import com.feedme.process.StaffProcess;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BHT
 */
public class StaffLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerLoginPanel
     */
    public StaffLoginPanel() {
        initComponents();
        //MainFrame.lblManagerName.setText(ManagerLoginPanel.txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStaffId = new javax.swing.JTextField();
        btnStaffLogin = new javax.swing.JButton();
        lblValidStaff = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("NHÂN VIÊN ĐĂNG NHẬP");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Tên Đăng Nhập");

        txtStaffId.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnStaffLogin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnStaffLogin.setText("Đăng Nhập");
        btnStaffLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffLoginActionPerformed(evt);
            }
        });

        lblValidStaff.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblValidStaff.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(btnStaffLogin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lblValidStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(568, 568, 568))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaffId)
                    .addComponent(lblValidStaff))
                .addGap(51, 51, 51)
                .addComponent(btnStaffLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(236, 236, 236))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaffLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffLoginActionPerformed

        new Thread(() -> {
            if (validateStaffLogin()) {
                try {
                    if (!StaffProcess.employeeLogin(Global.MANAGER, txtStaffId.getText())) {
                        JOptionPane.showMessageDialog(null, "Lỗi Đăng Nhập \n Vui lòng đăng nhập lại \n hoặc liên hệ với quản lý", "Lỗi Đăng Nhập", JOptionPane.ERROR_MESSAGE);

                    } else {
                        MainFrame.lblStaffName.setText("Nhân viên "+txtStaffId.getText());
                        CardLayout layout = (CardLayout) this.getParent().getLayout();
                        layout.next(this.getParent());
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Lỗi Đăng Nhập \n Vui lòng đăng nhập lại \n hoặc liên hệ với quản lý", "Lỗi Đăng Nhập", JOptionPane.ERROR_MESSAGE);
                    e.getMessage();
                }
            }
        }).start();
    }//GEN-LAST:event_btnStaffLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStaffLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblValidStaff;
    private javax.swing.JTextField txtStaffId;
    // End of variables declaration//GEN-END:variables



    private boolean validateStaffLogin() {
        if (txtStaffId.equals("")) {
            lblValidStaff.setText("Tên Đăng Nhập Không Được Bỏ Trống");
            return false;
        }
        return true;

    }
}
